// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Belt_Float = require("bs-platform/lib/js/belt_Float.js");

var userInfo = {
  contents: [
    {
      factor: 1.0,
      fcn: (function (prim) {
          return Math.sin(prim);
        }),
      theta: 1.0,
      offset: 0.0
    },
    {
      factor: 1.0,
      fcn: (function (prim) {
          return Math.sin(prim);
        }),
      theta: 1.0,
      offset: 0.0
    }
  ]
};

function getNumericValue(domId, $$default) {
  var stringValue = document.getElementById(domId).value;
  if (stringValue === "") {
    return $$default;
  }
  var value = Belt_Float.fromString(stringValue);
  if (value !== undefined) {
    return value;
  } else {
    return $$default;
  }
}

function getFunctionValue(domId) {
  if (document.getElementById(domId).value === "sin") {
    return function (prim) {
      return Math.sin(prim);
    };
  } else {
    return function (prim) {
      return Math.cos(prim);
    };
  }
}

function getFormula(suffix) {
  return {
          factor: getNumericValue("factor" + suffix, 1.0),
          fcn: getFunctionValue("fcn" + suffix),
          theta: getNumericValue("theta" + suffix, 1.0),
          offset: getNumericValue("offset" + suffix, 0.0)
        };
}

function getTypeOfGraph(param) {
  if (document.getElementById("polar").checked) {
    return /* Polar */0;
  } else {
    return /* Lissajous */1;
  }
}

exports.userInfo = userInfo;
exports.getNumericValue = getNumericValue;
exports.getFunctionValue = getFunctionValue;
exports.getFormula = getFormula;
exports.getTypeOfGraph = getTypeOfGraph;
/* No side effect */
